name: Deploy Frontend App with Docker

on:
  workflow_dispatch:
    inputs:
      target-env:
        required: true
        type: environment

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.target-env }}
    steps:
    - name: Logs
      run: |
        echo '### The deployment is made on the `${{ inputs.target-env }}` machine' >> $GITHUB_STEP_SUMMARY
      
    - uses: actions/checkout@v4
    - name: set vars
      id: vars
      run: |
        echo ::set-output name=BRANCH::${GITHUB_REF#refs/heads/}
        echo ::set-output name=HASH::$(git rev-parse --short ${GITHUB_SHA})
        echo ::set-output name=DATE::$(date +'%d-%m-%Y')
    - name: set imagename
      id: imagename
      run: |
        echo '### Name image: `${{ steps.imagename.outputs.IMAGENAME }}:${{ steps.vars.outputs.HASH }}` ' >> $GITHUB_STEP_SUMMARY
        echo ::set-output name=IMAGENAME::${t-bc-frontend-${{ steps.vars.outputs.BRANCH }}-${{ steps.vars.outputs.DATE }}} 
        
    - name: build
      run: |
        docker build . -t cr.yandex/${{ vars.ID_CONTAINER_REGISTRY }}/${{ steps.imagename.outputs.IMAGENAME }}:${{ steps.vars.outputs.HASH }}
    - name: Login to Yandex Cloud Container Registry
      id: login-cr
      uses: yc-actions/yc-cr-login@v1
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

    - name: upload in Container Registry
      run: |
        docker push cr.yandex/${{ vars.ID_CONTAINER_REGISTRY }}/${{ steps.imagename.outputs.IMAGENAME }}:${{ steps.vars.outputs.HASH }}
    - name: connect to vm and deploy 
      uses: appleboy/ssh-action@v1.0.0
      env: 
        IMAGE: cr.yandex/${{ vars.ID_CONTAINER_REGISTRY }}/${{ steps.imagename.outputs.IMAGENAME }}:${{ steps.vars.outputs.HASH }}
      with:
        host: ${{ vars.HOST }}
        username: ${{ vars.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ vars.PORT }}
        proxy_host: ${{ vars.PROXY_HOST }}
        proxy_username: ${{ vars.PROXY_USERNAME }}
        proxy_key: ${{ secrets.PROXY_KEY }}
        proxy_port: ${{ vars.PROXY_PORT }}
        envs: IMAGE
        script: |
          docker stop last_frontend
          docker rm last_frontend
          docker pull $IMAGE
          docker run -d --net=host --restart=always --name=last_frontend $IMAGE
